### PR TITLE
add selector for the login submit button in nextcloud 25

### PR DESCRIPTION
**Pull request by ylebre**
This adds a CSS selector for puppeteer so it can find the 'login' submit button in Nextcloud 25.

### CODE REVIEW

**Review by michielbdejong — APPROVED** [review]
LGTM

**Comment by Potherca** [comment]
@michielbdejong Could you also push a new version to [Dockerhub](https://hub.docker.com/r/michielbdejong/nextcloud-cookie)?

For the long-run, should I add an MR for a GitHub workflow to automatically publish new Docker images?

**Comment by Potherca** [comment]
On second thought... Automating this might make more sense to either use the [GitHub Container Registry](https://ghcr.io/) or the [PDS Interop Dockerhub](https://hub.docker.com/orgs/pdsinterop/). :thinking:

**Comment by michielbdejong** [comment]
https://hub.docker.com/r/michielbdejong/nextcloud-cookie updated
https://hub.docker.com/r/pdsinterop/nextcloud-cookie created

**Comment by Potherca** [comment]
Awesome! Thanks!

**Pull request merged**
